name: CI/CD
run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup go 1.22.6
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.6

    - name: Build go binary
      run: go build -o main .

    - name: go Test
      run: go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.59.1

  push to Ecr:
    runs-on:  ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure Aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Declare some variables
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
        
    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: public.ecr.aws
        REPOSITORY: go-web
        REGISTRY_ALIAS: c8n6i5p5
        IMAGE_TAG: ${{ env.sha_short }}
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        sed -i 's/tag: .*/tag: "${{"sha_short}}"/' helm/go-web-app-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "skrahamanskk@gmail.com"
        git config --global user.name "sshaik71"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Dyamically Updated tag in Helm chart"
        git push
    
